apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
spec:
  containers:
  - name: privileged-container
    image: busybox  # or any other simple image that you can use to access the system
    command: ["sleep", "3600"]  # Keep the pod running for an extended period
    securityContext:
      privileged: true  # This grants elevated privileges to the container
      capabilities:
        add: ["NET_ADMIN", "SYS_ADMIN"]  # These capabilities allow network and system administration actions
  # You could also mount sensitive host paths here (if applicable)
