name: Build

on:
  push:
    branches:
      - \"**\"  # Runs on push to any branch
  pull_request:
    branches:
      - \"**\"  # Runs on PRs for any branch

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history for better analysis

      - uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: \${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: \${{ secrets.SONAR_HOST_URL }}

      # Uncomment the next block to enforce Quality Gate checks
      # - uses: SonarSource/sonarqube-quality-gate-action@v1
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: \${{ secrets.SONAR_TOKEN }}